development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:a6091547a4f4b76a11e968107fa7c5d4@angelfish.redistogo.com:9327/
  channel_prefix: vagabond_buy_and_sell_production
